export const FACULTIES = [
  "Faculty of Agriculture",
  "Faculty of Arts",
  "Faculty of Communication and Information Sciences",
  "Faculty of Education",
  "Faculty of Engineering and Technology",
  "Faculty of Environmental Sciences",
  "Faculty of Law",
  "Faculty of Life Sciences",
  "Faculty of Management Sciences",
  "Faculty of Pharmaceutical Sciences",
  "Faculty of Physical Sciences",
  "Faculty of Social Sciences",
  "Faculty of Veterinary Medicine",
  "College of Health Sciences",
] as const;

export const CAMPUS_LOCATIONS = [
  { id: "library", name: "University Library" },
  { id: "senate", name: "Senate Building" },
  { id: "faculty-arts", name: "Faculty of Arts" },
  { id: "faculty-sciences", name: "Faculty of Physical Sciences" },
  { id: "faculty-engineering", name: "Faculty of Engineering" },
  { id: "faculty-education", name: "Faculty of Education" },
  { id: "faculty-law", name: "Faculty of Law" },
  { id: "faculty-management", name: "Faculty of Management Sciences" },
  { id: "faculty-social-sciences", name: "Faculty of Social Sciences" },
  { id: "faculty-life-sciences", name: "Faculty of Life Sciences" },
  { id: "faculty-agriculture", name: "Faculty of Agriculture" },
  { id: "faculty-cis", name: "Faculty of CIS" },
  { id: "faculty-env", name: "Faculty of Environmental Sciences" },
  { id: "faculty-pharma", name: "Faculty of Pharmaceutical Sciences" },
  { id: "faculty-vet", name: "Faculty of Veterinary Medicine" },
  { id: "health-sciences", name: "College of Health Sciences" },
  { id: "auditorium", name: "University Auditorium" },
  { id: "stadium", name: "University Stadium" },
  { id: "cafeteria-1", name: "Cafeteria 1" },
  { id: "cafeteria-2", name: "Cafeteria 2" },
  { id: "student-center", name: "Student Centre" },
  { id: "hostel-block-a", name: "Hostel Block A" },
  { id: "hostel-block-b", name: "Hostel Block B" },
  { id: "hostel-block-c", name: "Hostel Block C" },
  { id: "admin-block", name: "Admin Block" },
  { id: "ict-center", name: "ICT Centre" },
  { id: "sports-complex", name: "Sports Complex" },
  { id: "parking-lot", name: "Main Parking Lot" },
  { id: "bus-stop", name: "Campus Bus Stop" },
  { id: "gate-main", name: "Main Gate" },
] as const;

export const ITEM_CATEGORIES = [
  { value: "ELECTRONICS", label: "Electronics" },
  { value: "ID_CARDS", label: "ID Cards" },
  { value: "CLOTHING", label: "Clothing" },
  { value: "BOOKS", label: "Books" },
  { value: "STATIONERY", label: "Stationery" },
  { value: "BAGS", label: "Bags" },
  { value: "KEYS", label: "Keys" },
  { value: "OTHER", label: "Other" },
] as const;

export const ITEM_STATUSES = [
  { value: "ACTIVE", label: "Active" },
  { value: "UNDER_REVIEW", label: "Under Review" },
  { value: "RECOVERED", label: "Recovered" },
  { value: "DISPOSED", label: "Disposed" },
] as const;
